### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by nemanjavuk** [LinkedDataFragments/Client.Java#15]
I can't install the Client.js because in the dependencies there is a "follow-redirects": "RubenVerborgh/follow-redirects#feature-requestproxy" that is unavailable. Any workaround?

**Comment by RubenVerborgh** [comment]
Let me restore that branch. (Note, this is actually an issue for [Client.js](https://github.com/LinkedDataFragments/Client.js).)

**Comment by RubenVerborgh** [comment]
I recreated [the branch](https://github.com/RubenVerborgh/follow-redirects/tree/feature-requestproxy).

Note: the branch was deleted because the latest develop [now depends on follow-redirects 1.x](https://github.com/LinkedDataFragments/Client.js/commit/7ecff3928dca0ff8588ae96854f247f0633644f8), as I took ownership of the follow-redirects package.

**Comment by nemanjavuk** [comment]
Thanks. And sorry, it was indeed for Client.js.

**Comment by RubenVerborgh** [comment]
I also published the latest develop as ldf-client 2.0.3, such that the latest version no longer depends on a customized fork.
